version: "3"
services:

  nginx:
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # nginxのログを.nginx/log に出力する
      - ./log:/var/log/nginx
      - .:/usr/share/nginx/html
    ports:
      - "4232:80"
    environment:
      TZ: "Asia/Tokyo"
